version: '3.1'

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: todo
    ports:
    - "27017:27017"
    volumes:
    - ./:/docker-entrypoint-initdb.d/
